## This module is to encapsulate all the DataBase operations in one place and make it reusable across the application.

## abstract aways rae DB queries from the API endpoints and make it easier to maintain and test the application.

## keeps DB logic seperate and resuable , making the app cleaner and more maintainable.

# refresh() : reloads the object form the DB to get autogenerated fields like (id) after an insert operation.


from sqlalchemy.orm import Session
import models, schemas


# ger all users from the DB
def get_all_users(db: Session):
    return db.query(models.UserModel).all()


# get a user by id from the DB
def get_user_by_id(db: Session, user_id: int):
    return db.query(models.UserModel).get(user_id)


# create a new user in the DB
def create_user(db: Session, user: schemas.UserCreate):
    ## if user.phone is None, then we can set it to a default value or leave it as None. Here we are leaving it as None. 
    db_user = models.UserModel(name=user.name, email=user.email, phone=user.phone)
    db.add(db_user)
    db.commit()
    db.refresh(db_user)  # refresh to get the autogenerated id
    return db_user


# update a user in the DB
def update_user(db: Session, user_id: int, user: schemas.UserUpdate):
    db_user = db.query(models.UserModel).get(user_id)
    if db_user:
        db_user.name = user.name if user.name is not None else db_user.name
        db_user.phone = user.phone if user.phone is not None else db_user.phone
        db.commit()
        db.refresh(db_user)
        return db_user
    # else
    return None


# delete a user from the DB
def delete_user(db: Session, user_id: int):
    db_user = db.query(models.UserModel).get(user_id)
    if db_user:
        db.delete(db_user)
        db.commit()
        return db_user
    # else
    return None